name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows
            binary-suffix: '.exe'
          - os: macos-latest
            platform: macos
            binary-suffix: ''
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution (exclude UI to prevent CLI build conflicts)
      run: |
        # Build projects individually to avoid CLI file lock from UI project dependency
        dotnet build src/DocxTemplate.Core/DocxTemplate.Core.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build src/DocxTemplate.Infrastructure/DocxTemplate.Infrastructure.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build src/DocxTemplate.CLI/DocxTemplate.CLI.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.Core.Tests/DocxTemplate.Core.Tests.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.Infrastructure.Tests/DocxTemplate.Infrastructure.Tests.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.CLI.Tests/DocxTemplate.CLI.Tests.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.TestUtilities/DocxTemplate.TestUtilities.csproj --configuration Release --no-restore --verbosity minimal
        # Build UI-related projects last, after CLI is already built
        dotnet build src/DocxTemplate.UI/DocxTemplate.UI.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.UI.Tests/DocxTemplate.UI.Tests.csproj --configuration Release --no-restore --verbosity minimal
        dotnet build tests/DocxTemplate.EndToEnd.Tests/DocxTemplate.EndToEnd.Tests.csproj --configuration Release --no-restore --verbosity minimal
      
    - name: Run unit tests
      run: |
        # Run tests excluding UI and E2E tests to avoid platform-specific issues in CI
        dotnet test tests/DocxTemplate.Core.Tests/DocxTemplate.Core.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
        dotnet test tests/DocxTemplate.Infrastructure.Tests/DocxTemplate.Infrastructure.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
        dotnet test tests/DocxTemplate.CLI.Tests/DocxTemplate.CLI.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      
    - name: Kill any remaining processes (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        # Kill any DocxTemplate processes that might be hanging
        Get-Process | Where-Object {$_.ProcessName -like "*DocxTemplate*"} | Stop-Process -Force -ErrorAction SilentlyContinue
        # Wait a moment for cleanup
        Start-Sleep -Seconds 2
        
    - name: Kill any remaining processes (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Kill any DocxTemplate processes that might be hanging
        pkill -f "DocxTemplate" || true
        # Wait a moment for cleanup
        sleep 2
      
    - name: Test Czech character handling
      shell: bash
      run: |
        echo "Testing Czech character handling on ${{ matrix.platform }}"
        # Create test file with Czech characters
        echo '{"název": "Testovací dokument", "město": "Brno", "ulice": "Údolní"}' > test-czech.json
        
        # Verify file contents
        if [ "${{ matrix.platform }}" = "windows" ]; then
          type test-czech.json || cat test-czech.json
        else
          cat test-czech.json
        fi
        
        # Clean up
        rm test-czech.json
      
    - name: Upload coverage reports to Codecov
      if: matrix.os == 'windows-latest'
      uses: codecov/codecov-action@v4
      with:
        directory: ./coverage
        fail_ci_if_error: false
        verbose: true
        
  package:
    name: Create Packages
    runs-on: windows-latest
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Create NuGet packages
      run: |
        # Build only what's needed for NuGet packages, exclude UI project to avoid CLI build conflicts
        dotnet pack src/DocxTemplate.Core/DocxTemplate.Core.csproj --configuration Release --output ./packages --verbosity minimal
        dotnet pack src/DocxTemplate.Infrastructure/DocxTemplate.Infrastructure.csproj --configuration Release --output ./packages --verbosity minimal
        dotnet pack src/DocxTemplate.CLI/DocxTemplate.CLI.csproj --configuration Release --output ./packages --verbosity minimal
        
    - name: Create Windows executable
      run: |
        # Build CLI executable directly without UI project dependencies
        dotnet publish src/DocxTemplate.CLI/DocxTemplate.CLI.csproj -c Release -r win-x64 --self-contained -o ./publish/win-x64 --verbosity minimal
        
    - name: Create macOS executable  
      run: |
        # Build CLI executable directly without UI project dependencies  
        dotnet publish src/DocxTemplate.CLI/DocxTemplate.CLI.csproj -c Release -r osx-x64 --self-contained -o ./publish/osx-x64 --verbosity minimal
        
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./packages/*.nupkg
        
    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: ./publish/*